// SPDX-License-Identifier: Apache-2.0
#include "../include/relation_mutator_schema.h"

#define CF_V2_ARRAY_SIZE(array) (sizeof(array) / sizeof((array)[0]))

static const uint8_t cf_v2_pclm_graph_magic[] = "PCLMGR01";

static const cf_v2_relation_field_schema_t cf_v2_pclm_graph_fields[] = {
  {0U, 1U, CF_V2_RELATION_FIELD_UNSIGNED_BOUNDARY, 0U, 1U},
  {1U, 1U, CF_V2_RELATION_FIELD_UNSIGNED_BOUNDARY, 0U, 1U},
  {2U, 1U, CF_V2_RELATION_FIELD_UNSIGNED_BOUNDARY, 0U, 1U},
  {3U, 1U, CF_V2_RELATION_FIELD_UNSIGNED_BOUNDARY, 0U, 1U},
  {4U, 1U, CF_V2_RELATION_FIELD_ENUM, 6U, 2U},
  {5U, 1U, CF_V2_RELATION_FIELD_UNSIGNED_BOUNDARY, 0U, 2U},
  {6U, 1U, CF_V2_RELATION_FIELD_ENUM, 6U, 2U},
  {7U, 1U, CF_V2_RELATION_FIELD_UNSIGNED_BOUNDARY, 0U, 2U},
  {8U, 1U, CF_V2_RELATION_FIELD_ENUM, 6U, 3U},
  {9U, 1U, CF_V2_RELATION_FIELD_ENUM, 6U, 3U},
  {10U, 1U, CF_V2_RELATION_FIELD_ENUM, 2U, 3U},
  {11U, 1U, CF_V2_RELATION_FIELD_UNSIGNED_BOUNDARY, 0U, 3U},
  {12U, 1U, CF_V2_RELATION_FIELD_UNSIGNED_BOUNDARY, 0U, 3U},
  {13U, 1U, CF_V2_RELATION_FIELD_ENUM, 2U, 4U},
  {14U, 1U, CF_V2_RELATION_FIELD_ENUM, 4U, 4U},
  {15U, 1U, CF_V2_RELATION_FIELD_UNSIGNED_BOUNDARY, 0U, 4U},
  {16U, 1U, CF_V2_RELATION_FIELD_UNSIGNED_BOUNDARY, 0U, 4U},
  {17U, 1U, CF_V2_RELATION_FIELD_ENUM, 2U, 5U},
  {18U, 2U, CF_V2_RELATION_FIELD_SIGNED_DELTA, 0U, 5U},
  {20U, 1U, CF_V2_RELATION_FIELD_ENUM, 2U, 6U},
  {21U, 1U, CF_V2_RELATION_FIELD_ENUM, 2U, 6U},
  {22U, 1U, CF_V2_RELATION_FIELD_ENUM, 3U, 6U},
  {23U, 1U, CF_V2_RELATION_FIELD_ENUM, 2U, 7U},
  {24U, 1U, CF_V2_RELATION_FIELD_ENUM, 2U, 7U},
  {25U, 1U, CF_V2_RELATION_FIELD_ENUM, 2U, 8U},
  {26U, 2U, CF_V2_RELATION_FIELD_SIGNED_DELTA, 0U, 8U},
  {28U, 16U, CF_V2_RELATION_FIELD_RAW, 0U, 9U},
  {44U, 1U, CF_V2_RELATION_FIELD_RAW, 0U, 10U},
  {45U, 3U, CF_V2_RELATION_FIELD_RAW, 0U, 10U},
};

const cf_v2_relation_mutator_schema_t cf_v2_relation_mutator_schema = {
  cf_v2_pclm_graph_magic,
  sizeof(cf_v2_pclm_graph_magic) - 1U,
  48U,
  1U,
  cf_v2_pclm_graph_fields,
  CF_V2_ARRAY_SIZE(cf_v2_pclm_graph_fields),
};
