#!/usr/bin/env bash
set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_FILE="$ROOT/work/setup.env"

FILTER_ROOT="${SMT_FUZZER_FILTER_ROOT:-/usr/lib/cups/filter}"
TEMPLATE_FILTER_ROOT="${SMT_TEMPLATE_FILTER_ROOT:-${SMT_FUZZER_TEMPLATE_FILTER_ROOT:-/data/pre-gsoc/cups-filters}}"
ASAN_ROOT="${SMT_FUZZER_ASAN_ROOT:-$ROOT/work/openprinting-asan}"
VENV_DIR="${SMT_FUZZER_VENV_DIR:-.venv}"
TARGET_CONFIG="${SMT_FUZZER_TARGET_CONFIG:-configs/parser_targets.yaml}"
TEMPLATE_CONFIG="${SMT_TEMPLATE_CONFIG:-configs/parser_targets_auto_hybrid.yaml}"
QUICK_DURATION="${SMT_FUZZER_QUICK_DURATION:-1}"
TEMPLATE_DURATION="${SMT_TEMPLATE_DURATION:-60}"
ASAN_DURATION="${SMT_FUZZER_ASAN_DURATION:-60}"
WORKERS="${SMT_FUZZER_WORKERS:-2}"
TEMPLATE_WORKERS="${SMT_TEMPLATE_WORKERS:-2}"
TIMEOUT_SEC="${SMT_FUZZER_TIMEOUT_SEC:-5}"
TEMPLATE_TIMEOUT_SEC="${SMT_TEMPLATE_TIMEOUT_SEC:-5}"
TEMPLATE_MAX_RUN_GB="${SMT_TEMPLATE_MAX_RUN_GB:-1}"

if [[ -r "$CONFIG_FILE" ]]; then
  # shellcheck disable=SC1090
  . "$CONFIG_FILE"
fi

if [[ -t 1 && "${TERM:-dumb}" != "dumb" ]]; then
  BOLD="$(printf '\033[1m')"
  DIM="$(printf '\033[2m')"
  RED="$(printf '\033[31m')"
  GREEN="$(printf '\033[32m')"
  YELLOW="$(printf '\033[33m')"
  RESET="$(printf '\033[0m')"
else
  BOLD=""
  DIM=""
  RED=""
  GREEN=""
  YELLOW=""
  RESET=""
fi

usage() {
  cat <<'EOF'
usage: scripts/setup_tui.sh [--status|--commands|--help]

Interactive setup menu for local parser-fuzzers initialization.

Options:
  --status     print current configuration and dependency status, then exit
  --commands   print commands matching the current configuration, then exit
  --help       show this help
EOF
}

venv_path() {
  case "$VENV_DIR" in
    /*) printf '%s\n' "$VENV_DIR" ;;
    *) printf '%s\n' "$ROOT/$VENV_DIR" ;;
  esac
}

python_bin() {
  local venv
  venv="$(venv_path)"
  if [[ -x "$venv/bin/python" ]]; then
    printf '%s\n' "$venv/bin/python"
  elif command -v python3 >/dev/null 2>&1; then
    command -v python3
  else
    printf '%s\n' "python3"
  fi
}

status_word() {
  if "$@" >/dev/null 2>&1; then
    printf '%sok%s' "$GREEN" "$RESET"
  else
    printf '%smissing%s' "$RED" "$RESET"
  fi
}

shell_quote() {
  printf '%q' "$1"
}

save_config() {
  mkdir -p "$ROOT/work"
  {
    echo "# Generated by scripts/setup_tui.sh"
    echo "SMT_FUZZER_FILTER_ROOT=$(shell_quote "$FILTER_ROOT")"
    echo "SMT_TEMPLATE_FILTER_ROOT=$(shell_quote "$TEMPLATE_FILTER_ROOT")"
    echo "SMT_FUZZER_ASAN_ROOT=$(shell_quote "$ASAN_ROOT")"
    echo "SMT_FUZZER_VENV_DIR=$(shell_quote "$VENV_DIR")"
    echo "SMT_FUZZER_TARGET_CONFIG=$(shell_quote "$TARGET_CONFIG")"
    echo "SMT_TEMPLATE_CONFIG=$(shell_quote "$TEMPLATE_CONFIG")"
    echo "SMT_FUZZER_QUICK_DURATION=$(shell_quote "$QUICK_DURATION")"
    echo "SMT_TEMPLATE_DURATION=$(shell_quote "$TEMPLATE_DURATION")"
    echo "SMT_FUZZER_ASAN_DURATION=$(shell_quote "$ASAN_DURATION")"
    echo "SMT_FUZZER_WORKERS=$(shell_quote "$WORKERS")"
    echo "SMT_TEMPLATE_WORKERS=$(shell_quote "$TEMPLATE_WORKERS")"
    echo "SMT_FUZZER_TIMEOUT_SEC=$(shell_quote "$TIMEOUT_SEC")"
    echo "SMT_TEMPLATE_TIMEOUT_SEC=$(shell_quote "$TEMPLATE_TIMEOUT_SEC")"
    echo "SMT_TEMPLATE_MAX_RUN_GB=$(shell_quote "$TEMPLATE_MAX_RUN_GB")"
  } >"$CONFIG_FILE"
  echo "[ok] saved $CONFIG_FILE"
}

pause() {
  if [[ -t 0 ]]; then
    printf '\nPress Enter to continue... '
    read -r _
  fi
}

clear_screen() {
  if [[ -t 1 && "${TERM:-dumb}" != "dumb" ]]; then
    printf '\033c'
  fi
}

read_default() {
  local prompt="$1"
  local default_value="$2"
  local value
  printf '%s [%s]: ' "$prompt" "$default_value"
  read -r value
  if [[ -z "$value" ]]; then
    printf '%s\n' "$default_value"
  else
    printf '%s\n' "$value"
  fi
}

yes_no() {
  local prompt="$1"
  local default_value="${2:-n}"
  local suffix="[y/N]"
  local answer
  if [[ "$default_value" == "y" ]]; then
    suffix="[Y/n]"
  fi
  printf '%s %s ' "$prompt" "$suffix"
  read -r answer
  if [[ -z "$answer" ]]; then
    answer="$default_value"
  fi
  [[ "$answer" == "y" || "$answer" == "Y" || "$answer" == "yes" || "$answer" == "YES" ]]
}

run_project_cmd() {
  local status
  local venv
  venv="$(venv_path)"
  printf '\n%s+%s' "$DIM" "$RESET"
  printf ' %q' "$@"
  printf '\n\n'
  (
    cd "$ROOT" || exit 2
    export PATH="$venv/bin:$PATH"
    export PYTHONPATH="$ROOT/src"
    export SMT_FUZZER_FILTER_ROOT="$FILTER_ROOT"
    "$@"
  )
  status=$?
  printf '\n[exit] %s\n' "$status"
  return "$status"
}

run_python_cmd() {
  local py
  py="$(python_bin)"
  run_project_cmd "$py" "$@"
}

count_filters() {
  local filters=(rastertopclx rastertoescpx pwgtoraster)
  local count=0
  local filter
  for filter in "${filters[@]}"; do
    if [[ -x "$FILTER_ROOT/$filter" ]]; then
      count=$((count + 1))
    fi
  done
  printf '%s/%s' "$count" "${#filters[@]}"
}

print_status() {
  local py
  py="$(python_bin)"

  cat <<EOF
${BOLD}parser-fuzzers setup${RESET}

Project:
  root           $ROOT
  local config   $CONFIG_FILE

Current configuration:
  filter root    $FILTER_ROOT
  template root  $TEMPLATE_FILTER_ROOT
  ASan root      $ASAN_ROOT
  venv           $VENV_DIR
  target config  $TARGET_CONFIG
  template config $TEMPLATE_CONFIG
  quick run      ${QUICK_DURATION}s, workers=$WORKERS, timeout=${TIMEOUT_SEC}s
  template run   ${TEMPLATE_DURATION}s, workers=$TEMPLATE_WORKERS, timeout=${TEMPLATE_TIMEOUT_SEC}s, max=${TEMPLATE_MAX_RUN_GB}GB
  ASan run       ${ASAN_DURATION}s, workers=$WORKERS, timeout=${TIMEOUT_SEC}s

Dependency status:
  python3        $(status_word command -v python3)
  selected py    $py
  PyYAML         $(status_word "$py" -c "import yaml")
  z3-solver      $(status_word "$py" -c "import z3")
  clang          $(status_word command -v clang)
  AFL++          afl-fuzz=$(status_word command -v afl-fuzz), afl-clang-fast=$(status_word command -v afl-clang-fast)
  filters        $(count_filters) minimal filters under $FILTER_ROOT
EOF
}

print_commands() {
  cat <<EOF
# Safe clone-only initialization
scripts/install_ubuntu_deps.sh --minimal -y
python3 -m venv $(shell_quote "$VENV_DIR")
$(shell_quote "$(venv_path)")/bin/python -m pip install -U pip
$(shell_quote "$(venv_path)")/bin/python -m pip install -e .
PATH=$(shell_quote "$(venv_path)/bin"):\$PATH scripts/run_smoke.sh

# Recommended quick target test
scripts/install_ubuntu_deps.sh --system-filters -y
scripts/check_cups_filters_targets.sh $(shell_quote "$FILTER_ROOT")
scripts/run_local_cups_filters_campaign.sh $(shell_quote "$FILTER_ROOT") $(shell_quote "$QUICK_DURATION") $(shell_quote "$WORKERS") $(shell_quote "$TIMEOUT_SEC") $(shell_quote "$TARGET_CONFIG")

# Template runner with an explicit filter root
PYTHONPATH=src python3 -m parser_fuzzers.cli multitarget-monitor \\
  --config $(shell_quote "$TEMPLATE_CONFIG") \\
  --work-root work/template-runner \\
  --filter-root $(shell_quote "$TEMPLATE_FILTER_ROOT") \\
  --workers $(shell_quote "$TEMPLATE_WORKERS") \\
  --timeout-sec $(shell_quote "$TEMPLATE_TIMEOUT_SEC") \\
  --duration-sec $(shell_quote "$TEMPLATE_DURATION") \\
  --max-run-gb $(shell_quote "$TEMPLATE_MAX_RUN_GB") \\
  --discard-stdout \\
  --discovery-mode coverage \\
  --scheduler novelty \\
  --runtime-skip \\
  --summary-mode concise \\
  --prune-uninteresting

# Isolated ASan build plan
scripts/install_ubuntu_deps.sh --asan-build -y
scripts/print_cups_filters_build_plan.sh $(shell_quote "$ASAN_ROOT")
scripts/run_asan_cups_filters_campaign.sh $(shell_quote "$ASAN_ROOT") $(shell_quote "$ASAN_DURATION") $(shell_quote "$WORKERS") $(shell_quote "$TIMEOUT_SEC") $(shell_quote "$TARGET_CONFIG")

# AFL++ environment check
scripts/install_ubuntu_deps.sh --afl -y
scripts/afl_build_env.sh
EOF
}

install_deps_menu() {
  local mode_choice
  local mode
  local args

  cat <<'EOF'
Install package group:
  1) minimal Python smoke dependencies
  2) system CUPS/cups-filters runtime
  3) local OpenPrinting ASan build dependencies
  4) AFL++ tooling
  5) all groups
EOF
  mode_choice="$(read_default "Select package group" "1")"
  case "$mode_choice" in
    1) mode="--minimal" ;;
    2) mode="--system-filters" ;;
    3) mode="--asan-build" ;;
    4) mode="--afl" ;;
    5) mode="--all" ;;
    *) echo "[warn] unknown selection; using --minimal"; mode="--minimal" ;;
  esac

  args=("$mode")
  if yes_no "Print apt commands only?" "y"; then
    args+=(--dry-run)
  elif yes_no "Pass -y to apt-get install?" "y"; then
    args+=(-y)
  fi
  run_project_cmd scripts/install_ubuntu_deps.sh "${args[@]}"
  pause
}

setup_python() {
  local venv
  local py
  venv="$(venv_path)"

  run_project_cmd python3 -m venv "$venv" || {
    pause
    return
  }
  py="$venv/bin/python"
  run_project_cmd "$py" -m pip install -U pip || {
    pause
    return
  }
  run_project_cmd "$py" -m pip install -e .
  pause
}

validate_smoke_tests() {
  run_python_cmd -m parser_fuzzers.cli validate --configs configs || true
  run_project_cmd scripts/run_smoke.sh || true
  run_python_cmd -m unittest discover -s tests || true
  pause
}

configure_menu() {
  local value
  local profile

  FILTER_ROOT="$(read_default "CUPS filter root" "$FILTER_ROOT")"
  TEMPLATE_FILTER_ROOT="$(read_default "Template runner filter root" "$TEMPLATE_FILTER_ROOT")"
  ASAN_ROOT="$(read_default "ASan work root" "$ASAN_ROOT")"
  VENV_DIR="$(read_default "Python venv directory" "$VENV_DIR")"
  QUICK_DURATION="$(read_default "Quick target duration seconds" "$QUICK_DURATION")"
  TEMPLATE_DURATION="$(read_default "Template runner duration seconds" "$TEMPLATE_DURATION")"
  ASAN_DURATION="$(read_default "ASan target duration seconds" "$ASAN_DURATION")"
  WORKERS="$(read_default "Worker count" "$WORKERS")"
  TEMPLATE_WORKERS="$(read_default "Template runner worker count" "$TEMPLATE_WORKERS")"
  TIMEOUT_SEC="$(read_default "Per-case timeout seconds" "$TIMEOUT_SEC")"
  TEMPLATE_TIMEOUT_SEC="$(read_default "Template runner timeout seconds" "$TEMPLATE_TIMEOUT_SEC")"
  TEMPLATE_MAX_RUN_GB="$(read_default "Template runner max run GB" "$TEMPLATE_MAX_RUN_GB")"

  cat <<'EOF'
Target profile:
  1) configs/parser_targets.yaml            recommended quick smoke
  2) configs/parser_targets_general.yaml    broader generic discovery
  3) configs/parser_targets_coverage.yaml   expanded coverage discovery
  4) custom path
EOF
  profile="$(read_default "Select target profile" "1")"
  case "$profile" in
    1) TARGET_CONFIG="configs/parser_targets.yaml" ;;
    2) TARGET_CONFIG="configs/parser_targets_general.yaml" ;;
    3) TARGET_CONFIG="configs/parser_targets_coverage.yaml" ;;
    4)
      value="$(read_default "Target config path" "$TARGET_CONFIG")"
      TARGET_CONFIG="$value"
      ;;
    *) echo "[warn] keeping $TARGET_CONFIG" ;;
  esac
  TEMPLATE_CONFIG="$(read_default "Template runner config path" "$TEMPLATE_CONFIG")"
  save_config
  pause
}

check_filters() {
  if [[ "$TARGET_CONFIG" == *coverage* ]]; then
    run_project_cmd scripts/check_cups_filters_targets.sh --coverage "$FILTER_ROOT" || true
  else
    run_project_cmd scripts/check_cups_filters_targets.sh "$FILTER_ROOT" || true
  fi
  pause
}

quick_campaign() {
  print_status
  if yes_no "Run the recommended quick target test now?" "y"; then
    run_project_cmd scripts/run_local_cups_filters_campaign.sh "$FILTER_ROOT" "$QUICK_DURATION" "$WORKERS" "$TIMEOUT_SEC" "$TARGET_CONFIG" || true
  fi
  pause
}

write_asan_plan() {
  local plan
  plan="$ASAN_ROOT/build_plan.sh"
  mkdir -p "$ASAN_ROOT"
  (
    cd "$ROOT" || exit 2
    scripts/print_cups_filters_build_plan.sh "$ASAN_ROOT"
  ) >"$plan"
  chmod +x "$plan"
  echo "[ok] wrote $plan"
  echo "[next] inspect it, then run: bash $(shell_quote "$plan")"
  if yes_no "Run the ASan build plan now? This may clone and build OpenPrinting projects." "n"; then
    run_project_cmd bash "$plan" || true
  fi
  pause
}

asan_campaign() {
  run_project_cmd scripts/run_asan_cups_filters_campaign.sh "$ASAN_ROOT" "$ASAN_DURATION" "$WORKERS" "$TIMEOUT_SEC" "$TARGET_CONFIG" || true
  pause
}

template_runner_campaign() {
  print_status
  TEMPLATE_FILTER_ROOT="$(read_default "Template runner filter root" "$TEMPLATE_FILTER_ROOT")"
  TEMPLATE_CONFIG="$(read_default "Template runner config" "$TEMPLATE_CONFIG")"
  TEMPLATE_DURATION="$(read_default "Template runner duration seconds" "$TEMPLATE_DURATION")"
  TEMPLATE_WORKERS="$(read_default "Template runner workers" "$TEMPLATE_WORKERS")"
  TEMPLATE_TIMEOUT_SEC="$(read_default "Template runner timeout seconds" "$TEMPLATE_TIMEOUT_SEC")"
  TEMPLATE_MAX_RUN_GB="$(read_default "Template runner max run GB" "$TEMPLATE_MAX_RUN_GB")"
  save_config

  if [[ ! -d "$TEMPLATE_FILTER_ROOT" ]]; then
    echo "[warn] template filter root does not exist: $TEMPLATE_FILTER_ROOT"
    if ! yes_no "Continue anyway?" "n"; then
      pause
      return
    fi
  else
    run_project_cmd scripts/check_cups_filters_targets.sh --coverage "$TEMPLATE_FILTER_ROOT" || true
    if ! yes_no "Run template runner with this path?" "y"; then
      pause
      return
    fi
  fi

  SMT_TEMPLATE_FILTER_ROOT="$TEMPLATE_FILTER_ROOT" \
  SMT_TEMPLATE_CONFIG="$TEMPLATE_CONFIG" \
  SMT_TEMPLATE_MAX_RUN_GB="$TEMPLATE_MAX_RUN_GB" \
  SMT_TEMPLATE_SKIP_FILTER_PROMPT=1 \
    run_project_cmd scripts/run_template_runner_campaign.sh \
      "$TEMPLATE_DURATION" "$TEMPLATE_WORKERS" "$TEMPLATE_TIMEOUT_SEC" "$TEMPLATE_CONFIG" || true
  pause
}

afl_menu() {
  local choice
  local target
  local config
  local binary

  cat <<'EOF'
AFL++:
  1) install/check package group
  2) print AFL++ compiler environment
  3) print sample afl-fuzz command
EOF
  choice="$(read_default "Select AFL++ action" "2")"
  case "$choice" in
    1)
      run_project_cmd scripts/install_ubuntu_deps.sh --afl --dry-run
      ;;
    2)
      run_project_cmd scripts/afl_build_env.sh
      ;;
    3)
      target="$(read_default "Target id" "ppd_ipp_parser")"
      config="$(read_default "AFL config A0-A4" "A1")"
      binary="$(read_default "Instrumented binary" "harnesses/bin/ppd_ipp_parser")"
      run_project_cmd scripts/run_afl.sh "$target" "$config" "$binary"
      ;;
    *)
      echo "[warn] unknown AFL++ action"
      ;;
  esac
  pause
}

safe_init() {
  setup_python
  validate_smoke_tests
}

main_menu() {
  local choice
  while true; do
    clear_screen
    print_status
    cat <<'EOF'

Menu:
  0) safe clone-only init: venv + pip install + validate/smoke/tests
  1) install Ubuntu dependencies
  2) configure paths and run sizes
  3) validate Python smoke and tests
  4) check local CUPS filter targets
  5) run recommended quick start target campaign
  6) write isolated ASan build script
  7) run isolated ASan campaign
  8) AFL++ setup and command helper
  9) run template runner campaign
  10) print commands for current config
  q) quit
EOF
    printf '\nSelect action: '
    read -r choice
    case "$choice" in
      0) safe_init ;;
      1) install_deps_menu ;;
      2) configure_menu ;;
      3) validate_smoke_tests ;;
      4) check_filters ;;
      5) quick_campaign ;;
      6) write_asan_plan ;;
      7) asan_campaign ;;
      8) afl_menu ;;
      9) template_runner_campaign ;;
      10) print_commands; pause ;;
      q|Q) save_config; exit 0 ;;
      *) echo "[warn] unknown action"; pause ;;
    esac
  done
}

case "${1:-}" in
  --help|-h)
    usage
    exit 0
    ;;
  --status)
    print_status
    exit 0
    ;;
  --commands)
    print_commands
    exit 0
    ;;
  "")
    main_menu
    ;;
  *)
    echo "unknown argument: $1" >&2
    usage >&2
    exit 2
    ;;
esac
