// SPDX-License-Identifier: Apache-2.0
#ifndef CUPSFILTERS_FUZZ_V3_PDF_GRAPH_ROUTE_H
#define CUPSFILTERS_FUZZ_V3_PDF_GRAPH_ROUTE_H

#include <stddef.h>
#include <stdint.h>
#include <string.h>

#define CF_V3_PDF_GRAPH_MAGIC "P2PGV301"
#define CF_V3_PDF_GRAPH_MAGIC_SIZE 8U
#define CF_V3_PDF_GRAPH_HEADER_SIZE 48U
#define CF_V3_PDF_GRAPH_FIXED_SIZE \
  (CF_V3_PDF_GRAPH_MAGIC_SIZE + CF_V3_PDF_GRAPH_HEADER_SIZE)
#define CF_V3_PDF_GRAPH_MAX_MATERIAL (4U * 1024U * 1024U)
#define CF_V3_PDF_GRAPH_MAX_INPUT \
  (CF_V3_PDF_GRAPH_FIXED_SIZE + CF_V3_PDF_GRAPH_MAX_MATERIAL)
#define CF_V3_PDF_GRAPH_ROUTE_OFFSET 47U
#define CF_V3_PDF_GRAPH_ROUTE_MASK 0x1fU
#define CF_V3_PDF_GRAPH_FLAG_FAITHFUL 0x80U

enum cf_v3_pdf_graph_route_e
{
  CF_V3_PDF_GRAPH_ROUTE_ANNOTATION_DIRECT = 0,
  CF_V3_PDF_GRAPH_ROUTE_BOOKLET_EMPTY_DIRECT,
  CF_V3_PDF_GRAPH_ROUTE_LAYOUT_DIRECT,
  CF_V3_PDF_GRAPH_ROUTE_OBJECT_VALID,
  CF_V3_PDF_GRAPH_ROUTE_PAGE_LAYOUT_VALID,
  CF_V3_PDF_GRAPH_ROUTE_BOOKLET_ORDER,
  CF_V3_PDF_GRAPH_ROUTE_NUP_ORDER,
  CF_V3_PDF_GRAPH_ROUTE_RESOURCE_REMAP,
  CF_V3_PDF_GRAPH_ROUTE_RESOURCE_CONTINUATION,
  CF_V3_PDF_GRAPH_ROUTE_RESOURCE_VALUE,
  CF_V3_PDF_GRAPH_ROUTE_RESOURCE_CROSS_TYPE,
  CF_V3_PDF_GRAPH_ROUTE_RESOURCE_REFILL,
  CF_V3_PDF_GRAPH_ROUTE_RESOURCE_LEXICAL,
  CF_V3_PDF_GRAPH_ROUTE_RESOURCE_LONG_NAME,
  CF_V3_PDF_GRAPH_ROUTE_NUP_DIRECT,
  CF_V3_PDF_GRAPH_ROUTE_ASCII85_RELATION,
  CF_V3_PDF_GRAPH_ROUTE_ANNOTATION_RELATION,
  CF_V3_PDF_GRAPH_ROUTE_FLATTEN_RELATION,
  CF_V3_PDF_GRAPH_ROUTE_OUTPUT_CAPACITY_RELATION,
  CF_V3_PDF_GRAPH_ROUTE_PARENT_RELATION,
  CF_V3_PDF_GRAPH_ROUTE_COUNT
};

static inline int
cf_v3_pdf_graph_input(const uint8_t *data, size_t size)
{
  return data && size >= CF_V3_PDF_GRAPH_FIXED_SIZE + 1U &&
         size <= CF_V3_PDF_GRAPH_MAX_INPUT &&
         !memcmp(data, CF_V3_PDF_GRAPH_MAGIC, CF_V3_PDF_GRAPH_MAGIC_SIZE);
}

static inline uint8_t *
cf_v3_pdf_graph_header(uint8_t *data)
{
  return data + CF_V3_PDF_GRAPH_MAGIC_SIZE;
}

static inline const uint8_t *
cf_v3_pdf_graph_const_header(const uint8_t *data)
{
  return data + CF_V3_PDF_GRAPH_MAGIC_SIZE;
}

static inline unsigned
cf_v3_pdf_graph_route(const uint8_t *header)
{
  return (header[CF_V3_PDF_GRAPH_ROUTE_OFFSET] &
          CF_V3_PDF_GRAPH_ROUTE_MASK) % CF_V3_PDF_GRAPH_ROUTE_COUNT;
}

static inline int
cf_v3_pdf_graph_faithful(const uint8_t *header)
{
  return (header[CF_V3_PDF_GRAPH_ROUTE_OFFSET] &
          CF_V3_PDF_GRAPH_FLAG_FAITHFUL) != 0U;
}

#endif
